#!/usr/bin/env python3
"""Generate the manual's supported games from GameMaps.hpp (stdlib only)."""

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "manual/CVGenie/sections/game-list.tex"


def game_list():
    source = (ROOT / "src/GameMaps.hpp").read_text()
    match = re.search(r'static const char\* NAMES\[NUM_GAMES\] = \{(.*?)\n\};',
                      source, re.S)
    if not match:
        raise ValueError("Cannot find NAMES catalog in GameMaps.hpp")
    names = [json.loads(value) for value in re.findall(r'"(?:[^"\\]|\\.)*"',
                                                       match.group(1))]
    if not names or len(names) != len(set(names)):
        raise ValueError("Game names must be nonempty and unique")
    # Escape text, never interpret game names as TeX commands.
    escapes = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%",
               "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
               "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    lines = ["% Generated by tools/update_game_list.py; do not edit.",
             r"\begin{itemize}"]
    # Presentation can be alphabetical; serialized IDs must stay in source order.
    for name in sorted(names):
        lines.append(r"\item " + "".join(escapes.get(c, c) for c in name))
    return "\n".join(lines + [r"\end{itemize}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed list is stale; write nothing")
    args = parser.parse_args()
    expected = game_list()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            parser.exit(1, "Game list is stale: run python3 tools/update_game_list.py\n")
        print("CV Genie manual game list is current")
    else:
        OUTPUT.write_text(expected)
        print("Updated manual/CVGenie/sections/game-list.tex")


if __name__ == "__main__":
    main()
